### PR TITLE
Translated till line 251

### PR DESCRIPTION
**Pull request by lucifertrj**
Hi @arshadkazmi42,

I had forgotten entirely about my assigned task to translate rendering lists.md. I have translated `rendering-lists.md` till line 250, waiting for review and feedback to proceed with the further translation. 

Kind regards,

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
Hi @lucifertrj 

Thank you for sending PR. I will suggest translating the whole file, then we can start the review process as we have faced issues before when we were working on partial translations and review. 

We try to translate the whole file in a go and then we review the translation in parts.

You can let me know once the translation of whole file is completed, post that I can start the review.

**Comment by lucifertrj** [comment]
> to translate the whole file in

Sure

**Review by yogesharma12 — COMMENTED** [review]
Hi @lucifertrj 
I have a suggestion . Please keep some keywords in English Itself . Like Array and the function Recipeलिस्ट could have been RecipeList only.
and घटक could be कंपोनेंट

**Comment by arshadkazmi42** [comment]
> Hi @lucifertrj I have a suggestion . Please keep some keywords in English Itself . Like Array and the function Recipeलिस्ट could have been RecipeList only. and घटक could be कंपोनेंट

Thank you for pointing that out @yogesharma12
Just to add to that for component we use `कौम्पोनॅन्ट`

**Pull request closed without merging**
